# Generated by Django 5.2.8 on 2025-11-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aistore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
