# Generated by Django 5.2.8 on 2025-11-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistore', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='aistore_cus_last_na_dcc8ac_idx'),
        ),
    ]
