# Generated by Django 5.2.8 on 2025-11-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistore', '0004_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-', null=True),
        ),
    ]
