# Generated by Django 5.2.8 on 2025-11-29 01:59

import django
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('aistore', '0005_alter_customer_birth_day_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory', models.PositiveSmallIntegerField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aistore.collection')),
                ('promotions', models.ManyToManyField(blank=True, to='aistore.promotion')),
            ],
        ),

    ]
