# Generated by Django 5.2.8 on 2025-11-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistore', '0006_auto_20251129_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-', null=True),
        ),
    ]
