insert into aistore_collection (id, title) values (1, 'Toys');
insert into aistore_collection (id, title) values (2, 'Travel');
insert into aistore_collection (id, title) values (3, 'Food - Snacks');
insert into aistore_collection (id, title) values (4, 'Kitchen');
insert into aistore_collection (id, title) values (5, 'Food - Snacks');
insert into aistore_collection (id, title) values (6, 'Kitchen');
insert into aistore_collection (id, title) values (7, 'Food - Baking');
insert into aistore_collection (id, title) values (8, 'Food - Seafood');
insert into aistore_collection (id, title) values (9, 'Food - Spices');
insert into aistore_collection (id, title) values (10, 'Home');
insert into aistore_collection (id, title) values (11, 'Toys');
insert into aistore_collection (id, title) values (12, 'Home');
insert into aistore_collection (id, title) values (13, 'Automotive');
insert into aistore_collection (id, title) values (14, 'Fitness');
insert into aistore_collection (id, title) values (15, 'Food - Baking');
insert into aistore_collection (id, title) values (16, 'Food - Nuts');
insert into aistore_collection (id, title) values (17, 'Food - Snacks');
insert into aistore_collection (id, title) values (18, 'Food - Snacks');
insert into aistore_collection (id, title) values (19, 'Clothing - Footwear');
insert into aistore_collection (id, title) values (20, 'Food - Meat Substitutes');
insert into aistore_collection (id, title) values (21, 'Food - Seafood');
insert into aistore_collection (id, title) values (22, 'Food - Frozen Foods');
insert into aistore_collection (id, title) values (23, 'Food - Produce');
insert into aistore_collection (id, title) values (24, 'Office');
insert into aistore_collection (id, title) values (25, 'Health');
insert into aistore_collection (id, title) values (26, 'Food - Desserts');
insert into aistore_collection (id, title) values (27, 'Office');
insert into aistore_collection (id, title) values (28, 'Garden');
insert into aistore_collection (id, title) values (29, 'Kitchen');
insert into aistore_collection (id, title) values (30, 'Food - Condiments');
insert into aistore_collection (id, title) values (31, 'Food - Dairy');
insert into aistore_collection (id, title) values (32, 'Food - Snacks');
insert into aistore_collection (id, title) values (33, 'Pets');
insert into aistore_collection (id, title) values (34, 'Food - Condiments');
insert into aistore_collection (id, title) values (35, 'Food - Spices');
insert into aistore_collection (id, title) values (36, 'Clothing - Dresses');
insert into aistore_collection (id, title) values (37, 'Pets');
insert into aistore_collection (id, title) values (38, 'Food - Baking');
insert into aistore_collection (id, title) values (39, 'Food - Snacks');
insert into aistore_collection (id, title) values (40, 'Food - Vegetables');
insert into aistore_collection (id, title) values (41, 'Clothing - Tops');
insert into aistore_collection (id, title) values (42, 'Food - Frozen Desserts');
insert into aistore_collection (id, title) values (43, 'Food - Freezer');
insert into aistore_collection (id, title) values (44, 'Home');
insert into aistore_collection (id, title) values (45, 'Pets');
insert into aistore_collection (id, title) values (46, 'Pets');
insert into aistore_collection (id, title) values (47, 'Beauty');
insert into aistore_collection (id, title) values (48, 'Home');
insert into aistore_collection (id, title) values (49, 'Food - Frozen Foods');
insert into aistore_collection (id, title) values (50, 'Clothing - Footwear');
