insert into aistore_address (customer_id, street, city) values (1, 'Pankratz', 'Ayamaru');
insert into aistore_address (customer_id, street, city) values (2, 'Jenifer', 'Pasiripis');
insert into aistore_address (customer_id, street, city) values (3, 'Birchwood', 'Urrao');
insert into aistore_address (customer_id, street, city) values (4, 'Little Fleur', 'Sarongan');
insert into aistore_address (customer_id, street, city) values (5, 'North', 'Géfyra');
insert into aistore_address (customer_id, street, city) values (6, 'Myrtle', 'Songjiang');
insert into aistore_address (customer_id, street, city) values (7, 'Golf View', 'Xian’an');
insert into aistore_address (customer_id, street, city) values (8, 'American', 'Pacaembu');
insert into aistore_address (customer_id, street, city) values (9, 'Hollow Ridge', 'Ciudad Vieja');
insert into aistore_address (customer_id, street, city) values (10, 'Lawn', 'Tanabi');
insert into aistore_address (customer_id, street, city) values (11, 'Twin Pines', 'Montonggamang');
insert into aistore_address (customer_id, street, city) values (12, 'Lyons', 'Boyeros');
insert into aistore_address (customer_id, street, city) values (13, 'Truax', 'Gubat');
insert into aistore_address (customer_id, street, city) values (14, 'Fordem', 'Wenjiao');
insert into aistore_address (customer_id, street, city) values (15, 'Kings', 'Balazar');
insert into aistore_address (customer_id, street, city) values (16, 'Hansons', 'Caicara');
insert into aistore_address (customer_id, street, city) values (17, 'Larry', 'Chico');
insert into aistore_address (customer_id, street, city) values (18, 'Sunbrook', 'Palermo');
insert into aistore_address (customer_id, street, city) values (19, 'Shelley', 'Gujiadian');
insert into aistore_address (customer_id, street, city) values (20, 'Anzinger', 'Baicun');
insert into aistore_address (customer_id, street, city) values (21, 'Spaight', 'Senahú');
insert into aistore_address (customer_id, street, city) values (22, 'Bartillon', 'San Rafael');
insert into aistore_address (customer_id, street, city) values (23, 'Eliot', 'Paris 12');
insert into aistore_address (customer_id, street, city) values (24, '2nd', 'Marisgama');
insert into aistore_address (customer_id, street, city) values (25, 'West', 'Polkowice');
insert into aistore_address (customer_id, street, city) values (26, 'Sycamore', 'Tinalmud');
insert into aistore_address (customer_id, street, city) values (27, '2nd', 'Maisons-Laffitte');
insert into aistore_address (customer_id, street, city) values (28, 'Grover', 'Drzewica');
insert into aistore_address (customer_id, street, city) values (29, 'Northview', 'Parakanpanjang');
insert into aistore_address (customer_id, street, city) values (30, 'Fallview', 'Cochrane');
insert into aistore_address (customer_id, street, city) values (31, 'Dexter', 'Tartagal');
insert into aistore_address (customer_id, street, city) values (32, 'International', 'Bāqim as Sūq');
insert into aistore_address (customer_id, street, city) values (33, 'Trailsway', 'Leicheng');
insert into aistore_address (customer_id, street, city) values (34, 'Mesta', 'Masaraway');
insert into aistore_address (customer_id, street, city) values (35, 'Warrior', 'Shanshi');
insert into aistore_address (customer_id, street, city) values (36, 'Dixon', 'Xinwo');
insert into aistore_address (customer_id, street, city) values (37, 'Becker', 'Huanggong');
insert into aistore_address (customer_id, street, city) values (38, 'Crowley', 'Staroshcherbinovskaya');
insert into aistore_address (customer_id, street, city) values (39, 'Anhalt', 'Jovellar');
insert into aistore_address (customer_id, street, city) values (40, 'Barnett', 'Tabuk');
insert into aistore_address (customer_id, street, city) values (41, 'Mallory', 'Gingsir');
insert into aistore_address (customer_id, street, city) values (42, 'Continental', 'Yuanba');
insert into aistore_address (customer_id, street, city) values (43, 'Northwestern', 'Thabazimbi');
insert into aistore_address (customer_id, street, city) values (44, 'Old Gate', 'Kumanovo');
insert into aistore_address (customer_id, street, city) values (45, 'Warbler', 'Binonga');
insert into aistore_address (customer_id, street, city) values (46, 'Nelson', 'Bezhta');
insert into aistore_address (customer_id, street, city) values (47, 'Fieldstone', 'Strängnäs');
insert into aistore_address (customer_id, street, city) values (48, 'West', 'North Vancouver');
insert into aistore_address (customer_id, street, city) values (49, 'Brown', 'Al Ḩumaydāt');
insert into aistore_address (customer_id, street, city) values (50, 'Eagan', 'Tumcon Ilawod');
insert into aistore_address (customer_id, street, city) values (51, 'Schurz', 'Cordeirópolis');
insert into aistore_address (customer_id, street, city) values (52, 'Buena Vista', 'Kakanj');
insert into aistore_address (customer_id, street, city) values (53, 'Texas', 'San Vicente');
insert into aistore_address (customer_id, street, city) values (54, 'Lyons', 'Meedhoo');
insert into aistore_address (customer_id, street, city) values (55, 'Fairfield', 'Macau');
insert into aistore_address (customer_id, street, city) values (56, 'Dakota', 'Ōta');
insert into aistore_address (customer_id, street, city) values (57, 'Elgar', 'As Suqaylibīyah');
insert into aistore_address (customer_id, street, city) values (58, 'Jenna', 'Puqi');
insert into aistore_address (customer_id, street, city) values (59, 'Crownhardt', 'Estribeiro');
insert into aistore_address (customer_id, street, city) values (60, 'American', 'Jeziorany');
insert into aistore_address (customer_id, street, city) values (61, 'Macpherson', 'Annan');
insert into aistore_address (customer_id, street, city) values (62, 'American Ash', 'Shiqiao');
insert into aistore_address (customer_id, street, city) values (63, 'New Castle', 'Kempele');
insert into aistore_address (customer_id, street, city) values (64, 'Lawn', 'Koilás');
insert into aistore_address (customer_id, street, city) values (65, 'Everett', 'Trelew');
insert into aistore_address (customer_id, street, city) values (66, 'New Castle', 'Babug');
insert into aistore_address (customer_id, street, city) values (67, 'Dorton', 'Bahir Dar');
insert into aistore_address (customer_id, street, city) values (68, 'Gale', 'El Refugio');
insert into aistore_address (customer_id, street, city) values (69, 'Spohn', 'Chivhu');
insert into aistore_address (customer_id, street, city) values (70, 'Sachs', 'Lhabupu');
insert into aistore_address (customer_id, street, city) values (71, 'Donald', 'Lyublino');
insert into aistore_address (customer_id, street, city) values (72, 'Morningstar', 'Tateyama');
insert into aistore_address (customer_id, street, city) values (73, 'Golden Leaf', 'Minle');
insert into aistore_address (customer_id, street, city) values (74, 'Jenifer', 'Aimadamodo');
insert into aistore_address (customer_id, street, city) values (75, 'Miller', 'Jarabacoa');
insert into aistore_address (customer_id, street, city) values (76, 'Farwell', 'Pouso Alegre');
insert into aistore_address (customer_id, street, city) values (77, 'Harbort', 'Gammad');
insert into aistore_address (customer_id, street, city) values (78, 'Hansons', 'Čerčany');
insert into aistore_address (customer_id, street, city) values (79, 'Harper', 'Bantawora');
insert into aistore_address (customer_id, street, city) values (80, 'Northridge', 'Geyuan');
insert into aistore_address (customer_id, street, city) values (81, 'Novick', 'Lewisporte');
insert into aistore_address (customer_id, street, city) values (82, 'Northridge', 'Ban Phan Don');
insert into aistore_address (customer_id, street, city) values (83, 'Steensland', 'Albrechtice');
insert into aistore_address (customer_id, street, city) values (84, 'Melody', 'Santa Rita');
insert into aistore_address (customer_id, street, city) values (85, 'Tennyson', 'Tianxin');
insert into aistore_address (customer_id, street, city) values (86, 'Burning Wood', 'Zamora');
insert into aistore_address (customer_id, street, city) values (87, 'Nancy', 'Jönköping');
insert into aistore_address (customer_id, street, city) values (88, 'Merchant', 'Santa Catalina');
insert into aistore_address (customer_id, street, city) values (89, 'Melby', 'Landi Kotal');
insert into aistore_address (customer_id, street, city) values (90, 'Iowa', 'Al Mashāf');
insert into aistore_address (customer_id, street, city) values (91, 'Birchwood', 'Xiadian');
insert into aistore_address (customer_id, street, city) values (92, 'La Follette', 'Gangkou');
insert into aistore_address (customer_id, street, city) values (93, 'Mallory', 'Rognedino');
insert into aistore_address (customer_id, street, city) values (94, 'Village Green', 'Lobito');
insert into aistore_address (customer_id, street, city) values (95, 'Sutteridge', 'Dhuusamarreeb');
insert into aistore_address (customer_id, street, city) values (96, 'Susan', 'Annecy');
insert into aistore_address (customer_id, street, city) values (97, 'Florence', 'Machagai');
insert into aistore_address (customer_id, street, city) values (98, 'Farragut', 'Punta Arenas');
insert into aistore_address (customer_id, street, city) values (99, 'Basil', 'Hinthada');
insert into aistore_address (customer_id, street, city) values (100, 'Lunder', 'Jince');
insert into aistore_address (customer_id, street, city) values (101, 'Hollow Ridge', 'Wonorejo Dua');
insert into aistore_address (customer_id, street, city) values (102, 'Claremont', 'Baryshevo');
insert into aistore_address (customer_id, street, city) values (103, 'Warbler', 'Sbo’o');
insert into aistore_address (customer_id, street, city) values (104, 'Briar Crest', 'Mashi');
insert into aistore_address (customer_id, street, city) values (105, 'Basil', 'Bantuanon');
insert into aistore_address (customer_id, street, city) values (106, 'Sutherland', 'Handan');
insert into aistore_address (customer_id, street, city) values (107, 'Nobel', 'Dankunku');
insert into aistore_address (customer_id, street, city) values (108, 'Lotheville', 'Xilópolis');
insert into aistore_address (customer_id, street, city) values (109, 'Caliangt', 'Guantian');
insert into aistore_address (customer_id, street, city) values (110, 'Fordem', 'Petrijevci');
insert into aistore_address (customer_id, street, city) values (111, 'Caliangt', 'Beidaihehaibin');
insert into aistore_address (customer_id, street, city) values (112, 'Sachs', 'Springfield');
insert into aistore_address (customer_id, street, city) values (113, '6th', 'Zuogaimanma');
insert into aistore_address (customer_id, street, city) values (114, 'Karstens', 'Xinqiao');
insert into aistore_address (customer_id, street, city) values (115, 'American', 'Khuzdār');
insert into aistore_address (customer_id, street, city) values (116, 'Leroy', 'Maoming');
insert into aistore_address (customer_id, street, city) values (117, 'Bartelt', 'Caçapava do Sul');
insert into aistore_address (customer_id, street, city) values (118, 'Moulton', '‘Eilabun');
insert into aistore_address (customer_id, street, city) values (119, 'Dennis', 'Jatirejo');
insert into aistore_address (customer_id, street, city) values (120, 'Bunker Hill', 'Évreux');
insert into aistore_address (customer_id, street, city) values (121, 'Lillian', 'Medeiros Neto');
insert into aistore_address (customer_id, street, city) values (122, 'Rowland', 'Charenton-le-Pont');
insert into aistore_address (customer_id, street, city) values (123, 'Ilene', 'Lom Sak');
insert into aistore_address (customer_id, street, city) values (124, 'Autumn Leaf', 'Duobaoshan');
insert into aistore_address (customer_id, street, city) values (125, 'Rowland', 'Binzhou');
insert into aistore_address (customer_id, street, city) values (126, 'Starling', 'Diepsloot');
insert into aistore_address (customer_id, street, city) values (127, 'Jana', 'Xian’an');
insert into aistore_address (customer_id, street, city) values (128, 'Union', 'Si Prachan');
insert into aistore_address (customer_id, street, city) values (129, 'Stephen', 'Jingtou');
insert into aistore_address (customer_id, street, city) values (130, 'Farmco', 'Lushan');
insert into aistore_address (customer_id, street, city) values (131, 'Utah', 'Cukangpanjang');
insert into aistore_address (customer_id, street, city) values (132, 'Judy', 'San Francisco');
insert into aistore_address (customer_id, street, city) values (133, 'Meadow Valley', 'Esperança');
insert into aistore_address (customer_id, street, city) values (134, 'Mcbride', 'Ar Rifā‘');
insert into aistore_address (customer_id, street, city) values (135, 'Algoma', 'Kyzylorda');
insert into aistore_address (customer_id, street, city) values (136, 'Ohio', 'Araguaína');
insert into aistore_address (customer_id, street, city) values (137, 'Eliot', 'Jianfeng');
insert into aistore_address (customer_id, street, city) values (138, 'Di Loreto', 'Smolyan');
insert into aistore_address (customer_id, street, city) values (139, 'Amoth', 'Bergen');
insert into aistore_address (customer_id, street, city) values (140, 'Nelson', 'Suzhou');
insert into aistore_address (customer_id, street, city) values (141, 'Northview', 'Mankoeng');
insert into aistore_address (customer_id, street, city) values (142, 'Pond', 'Coromandel');
insert into aistore_address (customer_id, street, city) values (143, 'Artisan', 'Ngurensiti');
insert into aistore_address (customer_id, street, city) values (144, 'Muir', 'Solotcha');
insert into aistore_address (customer_id, street, city) values (145, 'Bartillon', 'Cochabamba');
insert into aistore_address (customer_id, street, city) values (146, 'Briar Crest', 'Silongin');
insert into aistore_address (customer_id, street, city) values (147, 'Talisman', 'Kilinochchi');
insert into aistore_address (customer_id, street, city) values (148, 'Arapahoe', 'Tubajon');
insert into aistore_address (customer_id, street, city) values (149, 'Waywood', 'Baoshui');
insert into aistore_address (customer_id, street, city) values (150, 'Russell', 'Pampas');
insert into aistore_address (customer_id, street, city) values (151, 'Valley Edge', 'Seattle');
insert into aistore_address (customer_id, street, city) values (152, 'Melby', 'Bamiantong');
insert into aistore_address (customer_id, street, city) values (153, 'Maryland', 'La Agustina');
insert into aistore_address (customer_id, street, city) values (154, 'Atwood', 'Bangbayang');
insert into aistore_address (customer_id, street, city) values (155, 'Leroy', 'Bar-le-Duc');
insert into aistore_address (customer_id, street, city) values (156, 'Fairfield', 'Isfara');
insert into aistore_address (customer_id, street, city) values (157, 'Stephen', 'Muff');
insert into aistore_address (customer_id, street, city) values (158, 'Barnett', 'Danghara');
insert into aistore_address (customer_id, street, city) values (159, 'Holy Cross', 'Faratsiho');
insert into aistore_address (customer_id, street, city) values (160, 'Susan', 'Stockholm');
insert into aistore_address (customer_id, street, city) values (161, 'Mendota', 'Mahébourg');
insert into aistore_address (customer_id, street, city) values (162, 'Goodland', 'Dresden');
insert into aistore_address (customer_id, street, city) values (163, 'Bellgrove', 'Dazhan');
insert into aistore_address (customer_id, street, city) values (164, 'Fallview', 'Dongchen');
insert into aistore_address (customer_id, street, city) values (165, 'Dwight', 'Jadów');
insert into aistore_address (customer_id, street, city) values (166, 'Express', 'Serra de Santa Marinha');
insert into aistore_address (customer_id, street, city) values (167, 'Delladonna', 'Kute');
insert into aistore_address (customer_id, street, city) values (168, 'Basil', 'Jatisari');
insert into aistore_address (customer_id, street, city) values (169, 'Anzinger', 'Kolympári');
insert into aistore_address (customer_id, street, city) values (170, 'Sommers', 'Youchou');
insert into aistore_address (customer_id, street, city) values (171, 'Ridge Oak', 'Aix-en-Provence');
insert into aistore_address (customer_id, street, city) values (172, 'Sugar', 'Prokhladnyy');
insert into aistore_address (customer_id, street, city) values (173, 'Pennsylvania', 'Parczew');
insert into aistore_address (customer_id, street, city) values (174, 'Oriole', 'KwaMbonambi');
insert into aistore_address (customer_id, street, city) values (175, 'Northland', 'Wuxia');
insert into aistore_address (customer_id, street, city) values (176, 'Sugar', 'Pomahuaca');
insert into aistore_address (customer_id, street, city) values (177, 'Atwood', 'Auriflama');
insert into aistore_address (customer_id, street, city) values (178, 'Ridgeview', 'Futian');
insert into aistore_address (customer_id, street, city) values (179, 'Banding', 'Xiakou');
insert into aistore_address (customer_id, street, city) values (180, 'Londonderry', 'Pop Shahri');
insert into aistore_address (customer_id, street, city) values (181, 'Fair Oaks', 'Damaying');
insert into aistore_address (customer_id, street, city) values (182, 'Pearson', 'Quţūr');
insert into aistore_address (customer_id, street, city) values (183, 'Comanche', 'Khvorostyanka');
insert into aistore_address (customer_id, street, city) values (184, 'Red Cloud', 'Ishëm');
insert into aistore_address (customer_id, street, city) values (185, 'Chinook', 'Lyon');
insert into aistore_address (customer_id, street, city) values (186, 'Westridge', 'Kajuru');
insert into aistore_address (customer_id, street, city) values (187, 'Hoard', 'Xijiang');
insert into aistore_address (customer_id, street, city) values (188, 'Blue Bill Park', 'Molodizhne');
insert into aistore_address (customer_id, street, city) values (189, 'Lakewood Gardens', 'Pinheiro');
insert into aistore_address (customer_id, street, city) values (190, 'Dakota', 'Razan');
insert into aistore_address (customer_id, street, city) values (191, 'Briar Crest', 'Kthella e Epërme');
insert into aistore_address (customer_id, street, city) values (192, 'Garrison', 'Krasnyy Lyman');
insert into aistore_address (customer_id, street, city) values (193, 'Artisan', 'Thabazimbi');
insert into aistore_address (customer_id, street, city) values (194, 'Birchwood', 'Gangou');
insert into aistore_address (customer_id, street, city) values (195, 'Gerald', 'Göteborg');
insert into aistore_address (customer_id, street, city) values (196, 'Ilene', 'Labuhankananga');
insert into aistore_address (customer_id, street, city) values (197, 'Haas', 'Pantaibesar');
insert into aistore_address (customer_id, street, city) values (198, '2nd', 'Gizo');
insert into aistore_address (customer_id, street, city) values (199, 'Pepper Wood', 'Ciechanowiec');
insert into aistore_address (customer_id, street, city) values (200, 'Orin', 'Zhangshi');
insert into aistore_address (customer_id, street, city) values (201, 'Sutherland', 'Nevers');
insert into aistore_address (customer_id, street, city) values (202, 'International', 'Voždovac');
insert into aistore_address (customer_id, street, city) values (203, 'Golden Leaf', 'Šenčur');
insert into aistore_address (customer_id, street, city) values (204, 'East', 'Shihudang');
insert into aistore_address (customer_id, street, city) values (205, 'Sage', 'Grugul');
insert into aistore_address (customer_id, street, city) values (206, 'Clyde Gallagher', 'Cizhu');
insert into aistore_address (customer_id, street, city) values (207, 'Pepper Wood', 'Hatava');
insert into aistore_address (customer_id, street, city) values (208, 'Spenser', 'Tapayan');
insert into aistore_address (customer_id, street, city) values (209, 'Monterey', 'Lukovica pri Domžalah');
insert into aistore_address (customer_id, street, city) values (210, 'Drewry', 'Novoaleksandrovsk');
insert into aistore_address (customer_id, street, city) values (211, 'Florence', 'Rizal');
insert into aistore_address (customer_id, street, city) values (212, 'Hoepker', 'Bantul');
insert into aistore_address (customer_id, street, city) values (213, 'Merrick', 'Bambali');
insert into aistore_address (customer_id, street, city) values (214, 'Lakeland', 'Padangsidempuan');
insert into aistore_address (customer_id, street, city) values (215, 'Warrior', 'Castelo');
insert into aistore_address (customer_id, street, city) values (216, 'Havey', 'Kafue');
insert into aistore_address (customer_id, street, city) values (217, 'Gateway', 'Al Qadmūs');
insert into aistore_address (customer_id, street, city) values (218, 'Express', 'Phoenix');
insert into aistore_address (customer_id, street, city) values (219, 'Bluejay', 'Ruda Śląska');
insert into aistore_address (customer_id, street, city) values (220, 'Lillian', 'Masis');
insert into aistore_address (customer_id, street, city) values (221, 'Charing Cross', 'Prupuh');
insert into aistore_address (customer_id, street, city) values (222, 'Dixon', 'Veliko Tŭrnovo');
insert into aistore_address (customer_id, street, city) values (223, 'Farmco', 'Zhaocun');
insert into aistore_address (customer_id, street, city) values (224, 'Butterfield', 'Dal’neye Konstantinovo');
insert into aistore_address (customer_id, street, city) values (225, 'Fisk', 'Młynary');
insert into aistore_address (customer_id, street, city) values (226, 'Hauk', 'Toguchin');
insert into aistore_address (customer_id, street, city) values (227, 'Continental', 'Sumanding');
insert into aistore_address (customer_id, street, city) values (228, 'Oakridge', 'Bieto');
insert into aistore_address (customer_id, street, city) values (229, 'John Wall', 'Syktyvkar');
insert into aistore_address (customer_id, street, city) values (230, 'Upham', 'Calape');
insert into aistore_address (customer_id, street, city) values (231, 'Artisan', 'Terter');
insert into aistore_address (customer_id, street, city) values (232, 'Miller', 'Norfolk');
insert into aistore_address (customer_id, street, city) values (233, 'Superior', 'Strasbourg');
insert into aistore_address (customer_id, street, city) values (234, 'Holy Cross', 'Marilao');
insert into aistore_address (customer_id, street, city) values (235, 'Leroy', 'Kajan');
insert into aistore_address (customer_id, street, city) values (236, 'Oak', 'Tange Zhen');
insert into aistore_address (customer_id, street, city) values (237, 'Oneill', 'Bošovice');
insert into aistore_address (customer_id, street, city) values (238, 'Namekagon', 'Gaio');
insert into aistore_address (customer_id, street, city) values (239, 'Canary', 'Jalpatagua');
insert into aistore_address (customer_id, street, city) values (240, 'Weeping Birch', 'Krajan Karangsari');
insert into aistore_address (customer_id, street, city) values (241, 'Blaine', 'Kuruman');
insert into aistore_address (customer_id, street, city) values (242, 'Elka', 'Tegalgunung');
insert into aistore_address (customer_id, street, city) values (243, 'Springs', 'Jiangkou');
insert into aistore_address (customer_id, street, city) values (244, 'Russell', 'Moriyama');
insert into aistore_address (customer_id, street, city) values (245, 'Melby', 'Pandan Niog');
insert into aistore_address (customer_id, street, city) values (246, 'Canary', 'Santo Estêvão');
insert into aistore_address (customer_id, street, city) values (247, 'Dawn', 'Risālpur');
insert into aistore_address (customer_id, street, city) values (248, 'Jana', 'Sępólno Krajeńskie');
insert into aistore_address (customer_id, street, city) values (249, 'Transport', 'Boston');
insert into aistore_address (customer_id, street, city) values (250, 'Southridge', 'Ţūlkarm');
insert into aistore_address (customer_id, street, city) values (251, 'Tomscot', 'Cimanggu');
insert into aistore_address (customer_id, street, city) values (252, 'Nevada', 'Goz Beïda');
insert into aistore_address (customer_id, street, city) values (253, 'Atwood', 'San Marcos');
insert into aistore_address (customer_id, street, city) values (254, 'Nancy', 'Skarbimierz Osiedle');
insert into aistore_address (customer_id, street, city) values (255, 'Eliot', 'Bento Gonçalves');
insert into aistore_address (customer_id, street, city) values (256, 'Manufacturers', 'Cincinnati');
insert into aistore_address (customer_id, street, city) values (257, 'Sage', 'Jiang’an');
insert into aistore_address (customer_id, street, city) values (258, 'Ridgeway', 'Coronel');
insert into aistore_address (customer_id, street, city) values (259, 'Hagan', 'Jiawu');
insert into aistore_address (customer_id, street, city) values (260, 'Dovetail', 'Virje');
insert into aistore_address (customer_id, street, city) values (261, 'Charing Cross', 'Guji');
insert into aistore_address (customer_id, street, city) values (262, 'Harper', 'Mutengene');
insert into aistore_address (customer_id, street, city) values (263, 'Sage', 'Santa Lucia');
insert into aistore_address (customer_id, street, city) values (264, 'Holmberg', 'Kranuan');
insert into aistore_address (customer_id, street, city) values (265, 'Derek', 'Mandera');
insert into aistore_address (customer_id, street, city) values (266, 'Division', 'Jiaoba');
insert into aistore_address (customer_id, street, city) values (267, 'Paget', 'Kotabaru');
insert into aistore_address (customer_id, street, city) values (268, 'Esker', 'Kaltungo');
insert into aistore_address (customer_id, street, city) values (269, 'Bartillon', 'Gunung Sugih');
insert into aistore_address (customer_id, street, city) values (270, 'Elgar', 'Xindeng');
insert into aistore_address (customer_id, street, city) values (271, 'Dexter', 'Dessalines');
insert into aistore_address (customer_id, street, city) values (272, 'Clove', 'Bogorodsk');
insert into aistore_address (customer_id, street, city) values (273, 'Boyd', 'Miramichi');
insert into aistore_address (customer_id, street, city) values (274, 'Golf', 'Besançon');
insert into aistore_address (customer_id, street, city) values (275, 'Grasskamp', 'Maceió');
insert into aistore_address (customer_id, street, city) values (276, 'Oneill', 'Łukowa');
insert into aistore_address (customer_id, street, city) values (277, 'Schiller', 'San Jerónimo');
insert into aistore_address (customer_id, street, city) values (278, 'Hanson', 'Mikumi');
insert into aistore_address (customer_id, street, city) values (279, 'Gerald', 'Fengdian');
insert into aistore_address (customer_id, street, city) values (280, 'Logan', 'Xingang');
insert into aistore_address (customer_id, street, city) values (281, 'Artisan', 'Mantes-la-Jolie');
insert into aistore_address (customer_id, street, city) values (282, 'Oak Valley', 'Mojoagung');
insert into aistore_address (customer_id, street, city) values (283, 'Ramsey', 'Huangshagang');
insert into aistore_address (customer_id, street, city) values (284, 'Main', 'Xiema');
insert into aistore_address (customer_id, street, city) values (285, 'Eastlawn', 'Zbraslavice');
insert into aistore_address (customer_id, street, city) values (286, 'Cherokee', 'Cikubang');
insert into aistore_address (customer_id, street, city) values (287, 'Linden', 'Sośnie');
insert into aistore_address (customer_id, street, city) values (288, 'Mandrake', 'Hongyi');
insert into aistore_address (customer_id, street, city) values (289, 'Mesta', 'Cam Lộ');
insert into aistore_address (customer_id, street, city) values (290, 'Bayside', 'Hanover');
insert into aistore_address (customer_id, street, city) values (291, 'Sunnyside', 'Pambuhan');
insert into aistore_address (customer_id, street, city) values (292, 'Service', 'Ringin Kembar');
insert into aistore_address (customer_id, street, city) values (293, 'Texas', 'Suileng');
insert into aistore_address (customer_id, street, city) values (294, 'Reindahl', 'Sua');
insert into aistore_address (customer_id, street, city) values (295, 'Buell', 'Hafrsfjord');
insert into aistore_address (customer_id, street, city) values (296, 'Armistice', 'Strömsnäsbruk');
insert into aistore_address (customer_id, street, city) values (297, 'Mallory', 'Tambulig');
insert into aistore_address (customer_id, street, city) values (298, 'Arkansas', 'El Limon');
insert into aistore_address (customer_id, street, city) values (299, 'Ruskin', 'Jāsim');
insert into aistore_address (customer_id, street, city) values (300, '3rd', 'Eskilstuna');
insert into aistore_address (customer_id, street, city) values (301, 'Basil', 'San Francisco');
insert into aistore_address (customer_id, street, city) values (302, 'Sutteridge', 'Longtang');
insert into aistore_address (customer_id, street, city) values (303, 'Heffernan', 'Nueva Loja');
insert into aistore_address (customer_id, street, city) values (304, 'Orin', 'The Valley');
insert into aistore_address (customer_id, street, city) values (305, 'Ridgeview', 'Fort Portal');
insert into aistore_address (customer_id, street, city) values (306, 'Rutledge', 'Cavalões');
insert into aistore_address (customer_id, street, city) values (307, 'American Ash', 'Pozo Hondo');
insert into aistore_address (customer_id, street, city) values (308, 'Vahlen', 'Huaqiao');
insert into aistore_address (customer_id, street, city) values (309, 'Ronald Regan', 'Nagai');
insert into aistore_address (customer_id, street, city) values (310, 'Corry', 'Springfield');
insert into aistore_address (customer_id, street, city) values (311, 'Transport', 'Botshabelo');
insert into aistore_address (customer_id, street, city) values (312, 'Manitowish', 'Wanbu');
insert into aistore_address (customer_id, street, city) values (313, 'Mandrake', 'Storuman');
insert into aistore_address (customer_id, street, city) values (314, 'Acker', 'Eg-Uur');
insert into aistore_address (customer_id, street, city) values (315, 'Darwin', 'Paluan');
insert into aistore_address (customer_id, street, city) values (316, 'Meadow Valley', 'Lagunas');
insert into aistore_address (customer_id, street, city) values (317, 'Monument', 'Zhatay');
insert into aistore_address (customer_id, street, city) values (318, 'Russell', 'Maturín');
insert into aistore_address (customer_id, street, city) values (319, 'Bellgrove', 'Amman');
insert into aistore_address (customer_id, street, city) values (320, 'Almo', 'Ādīs Zemen');
insert into aistore_address (customer_id, street, city) values (321, 'Birchwood', 'Cidade Velha');
insert into aistore_address (customer_id, street, city) values (322, 'Milwaukee', 'Vinhais');
insert into aistore_address (customer_id, street, city) values (323, 'Harbort', 'Cisalakdesa');
insert into aistore_address (customer_id, street, city) values (324, 'Prentice', 'Al Başrah');
insert into aistore_address (customer_id, street, city) values (325, 'Hauk', 'Ban Talat Nua');
insert into aistore_address (customer_id, street, city) values (326, 'Hazelcrest', 'Illéla');
insert into aistore_address (customer_id, street, city) values (327, 'Arapahoe', 'Bijia');
insert into aistore_address (customer_id, street, city) values (328, 'Independence', 'Guotan');
insert into aistore_address (customer_id, street, city) values (329, 'Garrison', 'Shatrovo');
insert into aistore_address (customer_id, street, city) values (330, 'Nevada', 'Huajie');
insert into aistore_address (customer_id, street, city) values (331, 'Portage', 'Hedong');
insert into aistore_address (customer_id, street, city) values (332, 'Prairieview', 'El Carmen');
insert into aistore_address (customer_id, street, city) values (333, 'Burning Wood', 'Roma');
insert into aistore_address (customer_id, street, city) values (334, 'Jenna', 'Tangal');
insert into aistore_address (customer_id, street, city) values (335, 'Coolidge', 'Claremont');
insert into aistore_address (customer_id, street, city) values (336, 'Kenwood', 'Horgo');
insert into aistore_address (customer_id, street, city) values (337, 'Sugar', 'Youkounkoun');
insert into aistore_address (customer_id, street, city) values (338, 'Dexter', 'Huangbei');
insert into aistore_address (customer_id, street, city) values (339, 'Garrison', 'Bantacan');
insert into aistore_address (customer_id, street, city) values (340, 'Fairview', 'Delft');
insert into aistore_address (customer_id, street, city) values (341, 'Crownhardt', 'Tianfu');
insert into aistore_address (customer_id, street, city) values (342, 'Amoth', 'Tournon-sur-Rhône');
insert into aistore_address (customer_id, street, city) values (343, 'Sherman', 'Xiaocheng');
insert into aistore_address (customer_id, street, city) values (344, 'Mayfield', 'Shangdian');
insert into aistore_address (customer_id, street, city) values (345, 'Mifflin', 'Carahue');
insert into aistore_address (customer_id, street, city) values (346, 'Milwaukee', 'Yur’yev-Pol’skiy');
insert into aistore_address (customer_id, street, city) values (347, 'Hoepker', 'Tarbes');
insert into aistore_address (customer_id, street, city) values (348, 'Lotheville', 'Clisson');
insert into aistore_address (customer_id, street, city) values (349, 'Browning', 'Lunec');
insert into aistore_address (customer_id, street, city) values (350, 'Clemons', 'Saint-Jouan-des-Guérets');
insert into aistore_address (customer_id, street, city) values (351, 'Emmet', 'Boldumsaz');
insert into aistore_address (customer_id, street, city) values (352, '4th', 'Maca');
insert into aistore_address (customer_id, street, city) values (353, 'Kinsman', 'Roczyny');
insert into aistore_address (customer_id, street, city) values (354, 'Alpine', 'Montigny-lès-Metz');
insert into aistore_address (customer_id, street, city) values (355, 'New Castle', 'Tembongraja');
insert into aistore_address (customer_id, street, city) values (356, 'Fisk', 'Lahad Datu');
insert into aistore_address (customer_id, street, city) values (357, 'Northridge', 'Selce');
insert into aistore_address (customer_id, street, city) values (358, 'Village Green', 'Mieścisko');
insert into aistore_address (customer_id, street, city) values (359, 'Graceland', 'Pelasgía');
insert into aistore_address (customer_id, street, city) values (360, 'Warbler', 'Lima Pampa');
insert into aistore_address (customer_id, street, city) values (361, 'Meadow Valley', 'New York City');
insert into aistore_address (customer_id, street, city) values (362, 'Continental', 'Raydah');
insert into aistore_address (customer_id, street, city) values (363, 'Karstens', 'Briceni');
insert into aistore_address (customer_id, street, city) values (364, 'Petterle', 'Parigi');
insert into aistore_address (customer_id, street, city) values (365, 'Troy', 'Naranjos');
insert into aistore_address (customer_id, street, city) values (366, 'Moulton', 'Jämsänkoski');
insert into aistore_address (customer_id, street, city) values (367, 'Stephen', 'Łukowa');
insert into aistore_address (customer_id, street, city) values (368, 'Onsgard', 'Hechuan');
insert into aistore_address (customer_id, street, city) values (369, 'Larry', 'Majin');
insert into aistore_address (customer_id, street, city) values (370, 'Hanover', 'Urkarakh');
insert into aistore_address (customer_id, street, city) values (371, 'Lien', 'Dayan');
insert into aistore_address (customer_id, street, city) values (372, 'Union', 'Jiaojie');
insert into aistore_address (customer_id, street, city) values (373, 'Hazelcrest', 'Przytyk');
insert into aistore_address (customer_id, street, city) values (374, 'Alpine', 'Yunhe');
insert into aistore_address (customer_id, street, city) values (375, '8th', 'Tiandiba');
insert into aistore_address (customer_id, street, city) values (376, 'Ludington', 'Baoshui');
insert into aistore_address (customer_id, street, city) values (377, 'Fuller', 'Ulaan Khat');
insert into aistore_address (customer_id, street, city) values (378, 'Caliangt', 'Pucara');
insert into aistore_address (customer_id, street, city) values (379, 'Menomonie', 'Nakuru');
insert into aistore_address (customer_id, street, city) values (380, 'Dayton', 'Sv. Trojica v Slov. Goricah');
insert into aistore_address (customer_id, street, city) values (381, 'Texas', 'Saint-Félicien');
insert into aistore_address (customer_id, street, city) values (382, 'Schiller', 'Dachnoye');
insert into aistore_address (customer_id, street, city) values (383, 'Porter', 'Gérakas');
insert into aistore_address (customer_id, street, city) values (384, 'Anderson', 'Qiaojia');
insert into aistore_address (customer_id, street, city) values (385, 'School', 'Yandian');
insert into aistore_address (customer_id, street, city) values (386, 'Sachs', 'Boavista');
insert into aistore_address (customer_id, street, city) values (387, 'Bayside', 'Sidenreng');
insert into aistore_address (customer_id, street, city) values (388, 'Bunker Hill', 'Tonggakjati');
insert into aistore_address (customer_id, street, city) values (389, 'Cody', 'Guaratuba');
insert into aistore_address (customer_id, street, city) values (390, 'Dovetail', 'Panineungan');
insert into aistore_address (customer_id, street, city) values (391, 'Logan', 'Sibulan');
insert into aistore_address (customer_id, street, city) values (392, 'Talisman', 'Zalaegerszeg');
insert into aistore_address (customer_id, street, city) values (393, 'Acker', 'Kotri');
insert into aistore_address (customer_id, street, city) values (394, 'Cardinal', 'Nzérékoré');
insert into aistore_address (customer_id, street, city) values (395, 'Jenna', 'Magdeburg');
insert into aistore_address (customer_id, street, city) values (396, 'Green Ridge', 'Glagahan');
insert into aistore_address (customer_id, street, city) values (397, 'Donald', 'Wudian');
insert into aistore_address (customer_id, street, city) values (398, 'Lakewood Gardens', 'Tulung');
insert into aistore_address (customer_id, street, city) values (399, 'Eastlawn', 'El Paisnal');
insert into aistore_address (customer_id, street, city) values (400, 'Oneill', 'Shumyachi');
insert into aistore_address (customer_id, street, city) values (401, 'Longview', 'Chinameca');
insert into aistore_address (customer_id, street, city) values (402, 'Fairview', 'El Almendro');
insert into aistore_address (customer_id, street, city) values (403, 'Kinsman', 'São João do Campo');
insert into aistore_address (customer_id, street, city) values (404, 'Main', 'Heshui');
insert into aistore_address (customer_id, street, city) values (405, 'Coleman', 'Karasuk');
insert into aistore_address (customer_id, street, city) values (406, 'Atwood', 'Macau');
insert into aistore_address (customer_id, street, city) values (407, 'Fair Oaks', 'Changzheng');
insert into aistore_address (customer_id, street, city) values (408, 'School', 'Akora');
insert into aistore_address (customer_id, street, city) values (409, 'High Crossing', 'Xingou');
insert into aistore_address (customer_id, street, city) values (410, 'Welch', 'Liukou');
insert into aistore_address (customer_id, street, city) values (411, 'Sugar', 'Wongaya Kaja');
insert into aistore_address (customer_id, street, city) values (412, 'Autumn Leaf', 'Lubukalung');
insert into aistore_address (customer_id, street, city) values (413, 'Caliangt', 'Guizi');
insert into aistore_address (customer_id, street, city) values (414, 'Pankratz', 'Yanghuxiang');
insert into aistore_address (customer_id, street, city) values (415, 'Oak Valley', 'Bharatpur');
insert into aistore_address (customer_id, street, city) values (416, 'Mayer', 'Balinad');
insert into aistore_address (customer_id, street, city) values (417, 'Nobel', 'Xinle');
insert into aistore_address (customer_id, street, city) values (418, 'Comanche', 'Dingyan');
insert into aistore_address (customer_id, street, city) values (419, 'Fair Oaks', 'Cambebba');
insert into aistore_address (customer_id, street, city) values (420, 'Porter', 'Bueng Samakkhi');
insert into aistore_address (customer_id, street, city) values (421, 'Algoma', 'Telheira');
insert into aistore_address (customer_id, street, city) values (422, 'Northview', 'Dawuhanmangli');
insert into aistore_address (customer_id, street, city) values (423, 'Novick', 'Reykjanesbær');
insert into aistore_address (customer_id, street, city) values (424, 'Thierer', 'Tomioka');
insert into aistore_address (customer_id, street, city) values (425, 'Lakewood Gardens', 'Karanyowka');
insert into aistore_address (customer_id, street, city) values (426, 'Kinsman', 'Tarimbang');
insert into aistore_address (customer_id, street, city) values (427, 'Hallows', 'Caringin');
insert into aistore_address (customer_id, street, city) values (428, 'Summit', 'Kuala Lumpur');
insert into aistore_address (customer_id, street, city) values (429, 'Kedzie', 'Sidomulyo Kulon');
insert into aistore_address (customer_id, street, city) values (430, 'Lyons', 'Loučná nad Desnou');
insert into aistore_address (customer_id, street, city) values (431, 'Westerfield', 'Tulay');
insert into aistore_address (customer_id, street, city) values (432, 'Packers', 'Erdaohe');
insert into aistore_address (customer_id, street, city) values (433, 'Summit', 'Poykovskiy');
insert into aistore_address (customer_id, street, city) values (434, 'Hooker', 'Ganyi');
insert into aistore_address (customer_id, street, city) values (435, 'Rieder', 'Przesmyki');
insert into aistore_address (customer_id, street, city) values (436, 'Memorial', 'Sukorejo');
insert into aistore_address (customer_id, street, city) values (437, 'Roth', 'Höshööt');
insert into aistore_address (customer_id, street, city) values (438, 'Northwestern', 'Kashiwazaki');
insert into aistore_address (customer_id, street, city) values (439, 'Mosinee', 'Oświęcim');
insert into aistore_address (customer_id, street, city) values (440, 'Warner', 'Nanggela');
insert into aistore_address (customer_id, street, city) values (441, 'Hanover', 'Néa Karyá');
insert into aistore_address (customer_id, street, city) values (442, 'Reinke', 'Baliang');
insert into aistore_address (customer_id, street, city) values (443, 'Oak Valley', 'Malaga');
insert into aistore_address (customer_id, street, city) values (444, 'Fairfield', 'Zwedru');
insert into aistore_address (customer_id, street, city) values (445, 'Goodland', 'Kensington');
insert into aistore_address (customer_id, street, city) values (446, 'Kingsford', 'Ciemas');
insert into aistore_address (customer_id, street, city) values (447, 'Canary', 'Buenlag');
insert into aistore_address (customer_id, street, city) values (448, 'Judy', 'Wailolong');
insert into aistore_address (customer_id, street, city) values (449, 'Packers', 'Nyinqug');
insert into aistore_address (customer_id, street, city) values (450, 'Golden Leaf', 'Bardo');
insert into aistore_address (customer_id, street, city) values (451, 'Alpine', 'Janów');
insert into aistore_address (customer_id, street, city) values (452, 'Oakridge', 'Fuwayriţ');
insert into aistore_address (customer_id, street, city) values (453, 'Merrick', 'Dayr Dibwān');
insert into aistore_address (customer_id, street, city) values (454, 'Crescent Oaks', 'Wādī as Sīr');
insert into aistore_address (customer_id, street, city) values (455, 'Holy Cross', 'Clanwilliam');
insert into aistore_address (customer_id, street, city) values (456, 'Kings', 'Huxi');
insert into aistore_address (customer_id, street, city) values (457, 'Emmet', 'Novi Beograd');
insert into aistore_address (customer_id, street, city) values (458, 'Rutledge', 'Tawen Aobao');
insert into aistore_address (customer_id, street, city) values (459, 'Merry', 'Cáchira');
insert into aistore_address (customer_id, street, city) values (460, 'Stone Corner', 'Henglu');
insert into aistore_address (customer_id, street, city) values (461, 'Bartelt', 'Jiangqiao');
insert into aistore_address (customer_id, street, city) values (462, 'Boyd', 'Igrejinha');
insert into aistore_address (customer_id, street, city) values (463, 'Chive', 'Zelenograd');
insert into aistore_address (customer_id, street, city) values (464, 'Golf', 'Caruaru');
insert into aistore_address (customer_id, street, city) values (465, 'Graedel', 'Āshkhāneh');
insert into aistore_address (customer_id, street, city) values (466, 'Butterfield', 'Castelsarrasin');
insert into aistore_address (customer_id, street, city) values (467, 'Northwestern', 'Kaniów');
insert into aistore_address (customer_id, street, city) values (468, 'Longview', 'Yuntan');
insert into aistore_address (customer_id, street, city) values (469, 'Iowa', 'Kapotnya');
insert into aistore_address (customer_id, street, city) values (470, 'Pleasure', 'Nubma');
insert into aistore_address (customer_id, street, city) values (471, 'Dexter', 'Krasnokholmskiy');
insert into aistore_address (customer_id, street, city) values (472, 'Rowland', 'Poretskoye');
insert into aistore_address (customer_id, street, city) values (473, 'Redwing', 'Sancha');
insert into aistore_address (customer_id, street, city) values (474, 'Southridge', 'Micheng');
insert into aistore_address (customer_id, street, city) values (475, 'Bultman', 'Gunungsubang');
insert into aistore_address (customer_id, street, city) values (476, 'Donald', 'Pende');
insert into aistore_address (customer_id, street, city) values (477, 'Westport', 'Nueva Imperial');
insert into aistore_address (customer_id, street, city) values (478, 'Moose', 'Riit');
insert into aistore_address (customer_id, street, city) values (479, 'Schiller', 'Machachi');
insert into aistore_address (customer_id, street, city) values (480, 'Ridge Oak', 'Sidareja');
insert into aistore_address (customer_id, street, city) values (481, 'Larry', 'Sikur');
insert into aistore_address (customer_id, street, city) values (482, 'Mendota', 'Liutao');
insert into aistore_address (customer_id, street, city) values (483, 'Raven', 'Aberdeen');
insert into aistore_address (customer_id, street, city) values (484, 'Sullivan', 'Sabanagrande');
insert into aistore_address (customer_id, street, city) values (485, 'Brickson Park', 'Gedongmulyo');
insert into aistore_address (customer_id, street, city) values (486, 'Maple Wood', 'Zharkent');
insert into aistore_address (customer_id, street, city) values (487, 'Armistice', 'Shuangxiqiao');
insert into aistore_address (customer_id, street, city) values (488, 'Ramsey', 'Palmdale');
insert into aistore_address (customer_id, street, city) values (489, 'Vahlen', 'Suraż');
insert into aistore_address (customer_id, street, city) values (490, 'Grover', 'Potrerillos');
insert into aistore_address (customer_id, street, city) values (491, 'Lakewood Gardens', 'Tangzhuang');
insert into aistore_address (customer_id, street, city) values (492, 'Schurz', 'Lý Sơn');
insert into aistore_address (customer_id, street, city) values (493, 'Spohn', 'Brangsi');
insert into aistore_address (customer_id, street, city) values (494, 'Del Mar', 'Kladruby');
insert into aistore_address (customer_id, street, city) values (495, 'La Follette', 'Täby');
insert into aistore_address (customer_id, street, city) values (496, 'Thompson', 'Kingsport');
insert into aistore_address (customer_id, street, city) values (497, 'Di Loreto', 'Liquan Chengguanzhen');
insert into aistore_address (customer_id, street, city) values (498, 'Jenna', 'Vinica');
insert into aistore_address (customer_id, street, city) values (499, 'Carey', 'Migues');
insert into aistore_address (customer_id, street, city) values (500, 'Declaration', 'Parabcan');
insert into aistore_address (customer_id, street, city) values (501, 'Arizona', 'Wenping');
insert into aistore_address (customer_id, street, city) values (502, 'Onsgard', 'Houmt Souk');
insert into aistore_address (customer_id, street, city) values (503, 'Brentwood', 'Storozhevaya');
insert into aistore_address (customer_id, street, city) values (504, 'Kensington', 'Shaxi');
insert into aistore_address (customer_id, street, city) values (505, 'Packers', 'Niny');
insert into aistore_address (customer_id, street, city) values (506, 'Shelley', 'Tākestān');
insert into aistore_address (customer_id, street, city) values (507, 'Prentice', 'Sande São Martinho');
insert into aistore_address (customer_id, street, city) values (508, 'Maple Wood', 'Coishco');
insert into aistore_address (customer_id, street, city) values (509, 'Schmedeman', 'Stockholm');
insert into aistore_address (customer_id, street, city) values (510, 'Transport', 'Huze');
insert into aistore_address (customer_id, street, city) values (511, 'Moland', 'Hualfín');
insert into aistore_address (customer_id, street, city) values (512, 'Washington', 'Kota Bharu');
insert into aistore_address (customer_id, street, city) values (513, 'Orin', 'Malangabang');
insert into aistore_address (customer_id, street, city) values (514, 'Manufacturers', 'Caihua');
insert into aistore_address (customer_id, street, city) values (515, 'Golf View', 'Pende');
insert into aistore_address (customer_id, street, city) values (516, 'Bellgrove', 'Na Yung');
insert into aistore_address (customer_id, street, city) values (517, 'Victoria', 'Zhongben');
insert into aistore_address (customer_id, street, city) values (518, 'Katie', 'Frei');
insert into aistore_address (customer_id, street, city) values (519, 'Karstens', 'Vale');
insert into aistore_address (customer_id, street, city) values (520, 'Little Fleur', 'Montpellier');
insert into aistore_address (customer_id, street, city) values (521, 'Kingsford', 'São João Nepomuceno');
insert into aistore_address (customer_id, street, city) values (522, 'Reinke', 'Spasskoye');
insert into aistore_address (customer_id, street, city) values (523, 'Badeau', 'Kota Bharu');
insert into aistore_address (customer_id, street, city) values (524, 'Farwell', 'Miguel Hidalgo');
insert into aistore_address (customer_id, street, city) values (525, 'Burrows', 'El Bauga');
insert into aistore_address (customer_id, street, city) values (526, 'Porter', 'Tongxing');
insert into aistore_address (customer_id, street, city) values (527, 'Oriole', 'Dalan');
insert into aistore_address (customer_id, street, city) values (528, 'Sutherland', 'Pysznica');
insert into aistore_address (customer_id, street, city) values (529, 'Myrtle', 'Žandov');
insert into aistore_address (customer_id, street, city) values (530, 'Cascade', 'Columbus');
insert into aistore_address (customer_id, street, city) values (531, 'Roth', 'Oborniki Śląskie');
insert into aistore_address (customer_id, street, city) values (532, 'Moose', 'Cabusao');
insert into aistore_address (customer_id, street, city) values (533, 'Green Ridge', 'Luebo');
insert into aistore_address (customer_id, street, city) values (534, 'Clyde Gallagher', 'San Diego');
insert into aistore_address (customer_id, street, city) values (535, 'Pawling', 'Safonovo');
insert into aistore_address (customer_id, street, city) values (536, 'Hanson', 'Mthatha');
insert into aistore_address (customer_id, street, city) values (537, 'Bunker Hill', 'Zásmuky');
insert into aistore_address (customer_id, street, city) values (538, 'Pennsylvania', 'Vogar');
insert into aistore_address (customer_id, street, city) values (539, 'Briar Crest', 'Kota Bharu');
insert into aistore_address (customer_id, street, city) values (540, 'Waxwing', 'Monte Carmelo');
insert into aistore_address (customer_id, street, city) values (541, 'Leroy', 'Almaty');
insert into aistore_address (customer_id, street, city) values (542, 'Crowley', 'Nueva Imperial');
insert into aistore_address (customer_id, street, city) values (543, 'Old Gate', 'Kretinga');
insert into aistore_address (customer_id, street, city) values (544, 'Drewry', 'Frederiksberg');
insert into aistore_address (customer_id, street, city) values (545, 'Merrick', 'Kuznechikha');
insert into aistore_address (customer_id, street, city) values (546, 'Waxwing', 'Stockholm');
insert into aistore_address (customer_id, street, city) values (547, 'Golf', 'Nanwai');
insert into aistore_address (customer_id, street, city) values (548, 'Arkansas', 'Rouyuan');
insert into aistore_address (customer_id, street, city) values (549, 'Moland', 'Port Barton');
insert into aistore_address (customer_id, street, city) values (550, 'Maryland', 'Nyazura');
insert into aistore_address (customer_id, street, city) values (551, 'Lawn', 'Solna');
insert into aistore_address (customer_id, street, city) values (552, 'Oxford', 'Ondo');
insert into aistore_address (customer_id, street, city) values (553, 'Karstens', 'Nakhon Ratchasima');
insert into aistore_address (customer_id, street, city) values (554, 'Forest Dale', 'Mache');
insert into aistore_address (customer_id, street, city) values (555, 'Michigan', 'Bebedahan');
insert into aistore_address (customer_id, street, city) values (556, 'Weeping Birch', 'Aktau');
insert into aistore_address (customer_id, street, city) values (557, 'Stang', 'Banī Khallād');
insert into aistore_address (customer_id, street, city) values (558, 'Old Shore', 'Arapiraca');
insert into aistore_address (customer_id, street, city) values (559, 'Granby', 'Nizhniy Tagil');
insert into aistore_address (customer_id, street, city) values (560, 'Upham', 'Bobigny');
insert into aistore_address (customer_id, street, city) values (561, 'Graceland', 'Delgerhaan');
insert into aistore_address (customer_id, street, city) values (562, 'Surrey', 'Burgos');
insert into aistore_address (customer_id, street, city) values (563, 'Quincy', 'Sumbersari Wetan');
insert into aistore_address (customer_id, street, city) values (564, 'Thierer', 'Ituverava');
insert into aistore_address (customer_id, street, city) values (565, 'Grayhawk', 'Rokitno Szlacheckie');
insert into aistore_address (customer_id, street, city) values (566, 'Bellgrove', 'Talisay');
insert into aistore_address (customer_id, street, city) values (567, 'Swallow', 'Pácora');
insert into aistore_address (customer_id, street, city) values (568, 'Reindahl', 'Zoushi');
insert into aistore_address (customer_id, street, city) values (569, 'Dahle', 'Cambará');
insert into aistore_address (customer_id, street, city) values (570, 'Burning Wood', 'Longzhong');
insert into aistore_address (customer_id, street, city) values (571, 'Springs', 'Zhangping');
insert into aistore_address (customer_id, street, city) values (572, 'Melody', 'Bolaoit');
insert into aistore_address (customer_id, street, city) values (573, 'Sachtjen', 'Lancai');
insert into aistore_address (customer_id, street, city) values (574, 'Blue Bill Park', 'Tcholliré');
insert into aistore_address (customer_id, street, city) values (575, 'Atwood', 'Jacareí');
insert into aistore_address (customer_id, street, city) values (576, 'Steensland', 'Al Manāqil');
insert into aistore_address (customer_id, street, city) values (577, 'Portage', 'Florianópolis');
insert into aistore_address (customer_id, street, city) values (578, 'Sullivan', 'Chamlykskaya');
insert into aistore_address (customer_id, street, city) values (579, 'Scofield', 'Girang');
insert into aistore_address (customer_id, street, city) values (580, 'Pierstorff', 'Campana');
insert into aistore_address (customer_id, street, city) values (581, 'Crownhardt', 'Al Mughayyir');
insert into aistore_address (customer_id, street, city) values (582, 'Morrow', 'Guandi');
insert into aistore_address (customer_id, street, city) values (583, 'Orin', 'Wangsi');
insert into aistore_address (customer_id, street, city) values (584, 'Sherman', 'Biograd na Moru');
insert into aistore_address (customer_id, street, city) values (585, 'Vahlen', 'Puerto Rico');
insert into aistore_address (customer_id, street, city) values (586, 'Shopko', 'Varāmīn');
insert into aistore_address (customer_id, street, city) values (587, '8th', 'Vojkovice');
insert into aistore_address (customer_id, street, city) values (588, 'Westend', 'Pār Naogaon');
insert into aistore_address (customer_id, street, city) values (589, 'Tony', 'Imielin');
insert into aistore_address (customer_id, street, city) values (590, 'Tennyson', 'Thị Trấn Cao Phong');
insert into aistore_address (customer_id, street, city) values (591, 'Burning Wood', 'São Bartolomeu');
insert into aistore_address (customer_id, street, city) values (592, 'Hauk', 'Agoo');
insert into aistore_address (customer_id, street, city) values (593, 'Duke', 'Tantamayo');
insert into aistore_address (customer_id, street, city) values (594, 'Goodland', 'Vsevolozhsk');
insert into aistore_address (customer_id, street, city) values (595, 'Columbus', 'Fairbanks');
insert into aistore_address (customer_id, street, city) values (596, 'Helena', 'Langkap');
insert into aistore_address (customer_id, street, city) values (597, 'Waubesa', 'Şabbūrah');
insert into aistore_address (customer_id, street, city) values (598, 'Carberry', 'Hartola');
insert into aistore_address (customer_id, street, city) values (599, 'Katie', 'Naran-mandokhu Somon');
insert into aistore_address (customer_id, street, city) values (600, 'Orin', 'Shendang');
insert into aistore_address (customer_id, street, city) values (601, 'Kingsford', 'Dún Laoghaire');
insert into aistore_address (customer_id, street, city) values (602, 'Bashford', 'Pende');
insert into aistore_address (customer_id, street, city) values (603, 'Golf View', 'Arras');
insert into aistore_address (customer_id, street, city) values (604, 'Vidon', 'Pirapora');
insert into aistore_address (customer_id, street, city) values (605, 'Gale', 'Gurbuki');
insert into aistore_address (customer_id, street, city) values (606, 'Iowa', 'Hisai');
insert into aistore_address (customer_id, street, city) values (607, 'Superior', 'Cutral-Có');
insert into aistore_address (customer_id, street, city) values (608, 'Manufacturers', 'Strasbourg');
insert into aistore_address (customer_id, street, city) values (609, 'Di Loreto', 'Karangranjong');
insert into aistore_address (customer_id, street, city) values (610, 'Rusk', 'Yartsevo');
insert into aistore_address (customer_id, street, city) values (611, 'Paget', 'Hanover');
insert into aistore_address (customer_id, street, city) values (612, 'Debra', 'Bafilo');
insert into aistore_address (customer_id, street, city) values (613, 'Linden', 'Lleida');
insert into aistore_address (customer_id, street, city) values (614, 'Hayes', 'Figueira Castelo Rodrigo');
insert into aistore_address (customer_id, street, city) values (615, 'Kim', 'Bodzentyn');
insert into aistore_address (customer_id, street, city) values (616, 'Menomonie', 'Novolugovoye');
insert into aistore_address (customer_id, street, city) values (617, 'Victoria', 'Jisegumen');
insert into aistore_address (customer_id, street, city) values (618, 'Manufacturers', 'Erie');
insert into aistore_address (customer_id, street, city) values (619, 'Fremont', 'Kaliwates');
insert into aistore_address (customer_id, street, city) values (620, 'Northridge', 'Rainis');
insert into aistore_address (customer_id, street, city) values (621, 'Myrtle', 'Angoulême');
insert into aistore_address (customer_id, street, city) values (622, 'Leroy', 'Amiens');
insert into aistore_address (customer_id, street, city) values (623, 'Crest Line', 'Cockburn Town');
insert into aistore_address (customer_id, street, city) values (624, 'Hauk', 'Linqu');
insert into aistore_address (customer_id, street, city) values (625, 'Fairview', 'Tilburg');
insert into aistore_address (customer_id, street, city) values (626, 'Trailsway', 'Bisert’');
insert into aistore_address (customer_id, street, city) values (627, 'Green', 'Camlachie');
insert into aistore_address (customer_id, street, city) values (628, 'Gina', 'Seda');
insert into aistore_address (customer_id, street, city) values (629, 'Summerview', 'Pule');
insert into aistore_address (customer_id, street, city) values (630, 'Derek', 'Borabue');
insert into aistore_address (customer_id, street, city) values (631, 'Sunnyside', 'San Agustín Acasaguastlán');
insert into aistore_address (customer_id, street, city) values (632, 'Tony', 'Komyshany');
insert into aistore_address (customer_id, street, city) values (633, 'High Crossing', 'Chão de Couce');
insert into aistore_address (customer_id, street, city) values (634, 'Algoma', 'Vanadzor');
insert into aistore_address (customer_id, street, city) values (635, 'Tomscot', 'Pāvilosta');
insert into aistore_address (customer_id, street, city) values (636, 'Merry', 'Bujumbura');
insert into aistore_address (customer_id, street, city) values (637, 'Monterey', 'Santa Cruz do Bispo');
insert into aistore_address (customer_id, street, city) values (638, 'Forest Run', 'Anjepy');
insert into aistore_address (customer_id, street, city) values (639, 'Glendale', 'Novomoskovsk');
insert into aistore_address (customer_id, street, city) values (640, 'Eastlawn', 'Asunción Mita');
insert into aistore_address (customer_id, street, city) values (641, 'Nevada', 'Vicente Guerrero');
insert into aistore_address (customer_id, street, city) values (642, 'Oak', 'Tampakan');
insert into aistore_address (customer_id, street, city) values (643, 'Shelley', 'Shanghudi');
insert into aistore_address (customer_id, street, city) values (644, 'Hooker', 'Mosquera');
insert into aistore_address (customer_id, street, city) values (645, 'Stuart', 'Bingfang');
insert into aistore_address (customer_id, street, city) values (646, 'Pierstorff', 'Bato');
insert into aistore_address (customer_id, street, city) values (647, 'Sunnyside', 'Gafanha da Encarnação');
insert into aistore_address (customer_id, street, city) values (648, 'Maywood', 'Saint Louis');
insert into aistore_address (customer_id, street, city) values (649, 'Becker', 'Cheongpyeong');
insert into aistore_address (customer_id, street, city) values (650, 'Burrows', 'Ak’ordat');
insert into aistore_address (customer_id, street, city) values (651, 'Manley', 'Zheleznogorsk');
insert into aistore_address (customer_id, street, city) values (652, 'Chive', 'Qingkou');
insert into aistore_address (customer_id, street, city) values (653, 'Melvin', 'Daja Lorong');
insert into aistore_address (customer_id, street, city) values (654, 'Dapin', 'Sleman');
insert into aistore_address (customer_id, street, city) values (655, 'Manley', 'Atlanta');
insert into aistore_address (customer_id, street, city) values (656, 'Harbort', 'Landskrona');
insert into aistore_address (customer_id, street, city) values (657, 'Memorial', 'Podkumskiy');
insert into aistore_address (customer_id, street, city) values (658, 'Rutledge', 'Vilarelho');
insert into aistore_address (customer_id, street, city) values (659, 'Dennis', 'Dingli');
insert into aistore_address (customer_id, street, city) values (660, 'Namekagon', 'Likhoy');
insert into aistore_address (customer_id, street, city) values (661, 'Holmberg', 'Shaliu');
insert into aistore_address (customer_id, street, city) values (662, 'Mayfield', 'Luzhou');
insert into aistore_address (customer_id, street, city) values (663, 'Harper', 'Nogueira');
insert into aistore_address (customer_id, street, city) values (664, 'Sherman', 'Żelistrzewo');
insert into aistore_address (customer_id, street, city) values (665, 'Arapahoe', 'Putatbasiun');
insert into aistore_address (customer_id, street, city) values (666, 'Basil', 'Mỹ Thọ');
insert into aistore_address (customer_id, street, city) values (667, 'Tony', 'Iligan City');
insert into aistore_address (customer_id, street, city) values (668, 'Meadow Valley', 'Seattle');
insert into aistore_address (customer_id, street, city) values (669, 'Buhler', 'Alung');
insert into aistore_address (customer_id, street, city) values (670, 'Sherman', 'Badulla');
insert into aistore_address (customer_id, street, city) values (671, 'Anderson', 'Karangsonojabon');
insert into aistore_address (customer_id, street, city) values (672, 'Kensington', 'Stari Banovci');
insert into aistore_address (customer_id, street, city) values (673, 'Basil', 'Borzytuchom');
insert into aistore_address (customer_id, street, city) values (674, 'Boyd', 'Sātkania');
insert into aistore_address (customer_id, street, city) values (675, 'Bultman', 'Ganding');
insert into aistore_address (customer_id, street, city) values (676, 'Larry', 'Chattanooga');
insert into aistore_address (customer_id, street, city) values (677, 'Knutson', 'Unión');
insert into aistore_address (customer_id, street, city) values (678, 'Emmet', 'Stare Miasto');
insert into aistore_address (customer_id, street, city) values (679, 'New Castle', 'Beijós');
insert into aistore_address (customer_id, street, city) values (680, 'Upham', 'Infanta');
insert into aistore_address (customer_id, street, city) values (681, 'Wayridge', 'Ijūin');
insert into aistore_address (customer_id, street, city) values (682, 'Comanche', 'Kulunda');
insert into aistore_address (customer_id, street, city) values (683, '8th', 'Saint-Sauveur');
insert into aistore_address (customer_id, street, city) values (684, '3rd', 'Clervaux');
insert into aistore_address (customer_id, street, city) values (685, 'Talmadge', 'Perovo');
insert into aistore_address (customer_id, street, city) values (686, 'Springs', 'Sumberpinang Satu');
insert into aistore_address (customer_id, street, city) values (687, 'Pankratz', 'Morje');
insert into aistore_address (customer_id, street, city) values (688, 'Algoma', 'Godong');
insert into aistore_address (customer_id, street, city) values (689, 'Springview', 'Novokizhinginsk');
insert into aistore_address (customer_id, street, city) values (690, 'Corry', 'Oroquieta');
insert into aistore_address (customer_id, street, city) values (691, '4th', 'Wādī as Sīr');
insert into aistore_address (customer_id, street, city) values (692, 'Mosinee', 'Mariental');
insert into aistore_address (customer_id, street, city) values (693, 'Chinook', 'Desovo');
insert into aistore_address (customer_id, street, city) values (694, 'Weeping Birch', 'Yambio');
insert into aistore_address (customer_id, street, city) values (695, 'Prairie Rose', 'Sirinhaém');
insert into aistore_address (customer_id, street, city) values (696, 'Corry', 'Serere');
insert into aistore_address (customer_id, street, city) values (697, 'Pawling', 'Oulad Frej');
insert into aistore_address (customer_id, street, city) values (698, 'Clarendon', 'Skoczów');
insert into aistore_address (customer_id, street, city) values (699, 'Meadow Ridge', 'Kota Ternate');
insert into aistore_address (customer_id, street, city) values (700, 'Ridgeview', 'Kostelec nad Černými Lesy');
insert into aistore_address (customer_id, street, city) values (701, 'Clemons', 'Shofirkon');
insert into aistore_address (customer_id, street, city) values (702, 'Namekagon', 'Seattle');
insert into aistore_address (customer_id, street, city) values (703, 'Northridge', 'Dallas');
insert into aistore_address (customer_id, street, city) values (704, 'Victoria', 'Ridder');
insert into aistore_address (customer_id, street, city) values (705, 'South', 'Clermont-Ferrand');
insert into aistore_address (customer_id, street, city) values (706, 'Onsgard', 'Hagonoy');
insert into aistore_address (customer_id, street, city) values (707, 'Transport', 'San Isidro de Lules');
insert into aistore_address (customer_id, street, city) values (708, 'Homewood', 'Khanāşir');
insert into aistore_address (customer_id, street, city) values (709, 'Mockingbird', 'Yangxiang');
insert into aistore_address (customer_id, street, city) values (710, 'Killdeer', 'Lebu');
insert into aistore_address (customer_id, street, city) values (711, 'Golf Course', 'Armenta');
insert into aistore_address (customer_id, street, city) values (712, 'Paget', 'Terangun');
insert into aistore_address (customer_id, street, city) values (713, 'Paget', 'Kęsowo');
insert into aistore_address (customer_id, street, city) values (714, 'Porter', 'Oliveirinha');
insert into aistore_address (customer_id, street, city) values (715, 'Village Green', 'Amadora');
insert into aistore_address (customer_id, street, city) values (716, 'Reindahl', 'Joroan');
insert into aistore_address (customer_id, street, city) values (717, 'Luster', 'Tongqian');
insert into aistore_address (customer_id, street, city) values (718, 'Marquette', 'Jargalant');
insert into aistore_address (customer_id, street, city) values (719, 'Portage', 'Nong Muang');
insert into aistore_address (customer_id, street, city) values (720, 'Hermina', 'Shetan');
insert into aistore_address (customer_id, street, city) values (721, 'Fremont', 'Poyang');
insert into aistore_address (customer_id, street, city) values (722, 'Loeprich', 'Chortkiv');
insert into aistore_address (customer_id, street, city) values (723, 'Scofield', 'Ōami');
insert into aistore_address (customer_id, street, city) values (724, 'Cherokee', 'Yaguarón');
insert into aistore_address (customer_id, street, city) values (725, 'Grim', 'Jinghai');
insert into aistore_address (customer_id, street, city) values (726, 'Marquette', 'Balingoan');
insert into aistore_address (customer_id, street, city) values (727, 'Blackbird', 'Estarreja');
insert into aistore_address (customer_id, street, city) values (728, 'Katie', 'Toutuo');
insert into aistore_address (customer_id, street, city) values (729, 'Crownhardt', 'Currais');
insert into aistore_address (customer_id, street, city) values (730, 'Mifflin', 'Huangjin');
insert into aistore_address (customer_id, street, city) values (731, 'Butterfield', 'Illkirch-Graffenstaden');
insert into aistore_address (customer_id, street, city) values (732, 'Meadow Vale', 'Jessore');
insert into aistore_address (customer_id, street, city) values (733, 'Scott', 'Yujiawu');
insert into aistore_address (customer_id, street, city) values (734, 'Hagan', 'Colcabamba');
insert into aistore_address (customer_id, street, city) values (735, 'Stuart', 'Sobontoro');
insert into aistore_address (customer_id, street, city) values (736, 'Schlimgen', 'Mercedes');
insert into aistore_address (customer_id, street, city) values (737, 'Caliangt', 'Wenxi');
insert into aistore_address (customer_id, street, city) values (738, 'Hudson', 'Lexington');
insert into aistore_address (customer_id, street, city) values (739, 'Scott', 'San Andres');
insert into aistore_address (customer_id, street, city) values (740, 'Pepper Wood', 'Alakak');
insert into aistore_address (customer_id, street, city) values (741, 'Lyons', 'Ketang');
insert into aistore_address (customer_id, street, city) values (742, 'Dwight', 'Tarvasjoki');
insert into aistore_address (customer_id, street, city) values (743, 'Farwell', 'Fengshan');
insert into aistore_address (customer_id, street, city) values (744, 'Monica', 'Sebegen');
insert into aistore_address (customer_id, street, city) values (745, 'Esker', 'Sumberpandan');
insert into aistore_address (customer_id, street, city) values (746, 'Arizona', 'Katy');
insert into aistore_address (customer_id, street, city) values (747, 'Briar Crest', 'Buzet');
insert into aistore_address (customer_id, street, city) values (748, 'Roxbury', 'Kaeng Khro');
insert into aistore_address (customer_id, street, city) values (749, 'Southridge', 'Talok');
insert into aistore_address (customer_id, street, city) values (750, 'Stoughton', 'Talawi');
insert into aistore_address (customer_id, street, city) values (751, 'Westend', 'Besao');
insert into aistore_address (customer_id, street, city) values (752, 'Monterey', 'El Playón');
insert into aistore_address (customer_id, street, city) values (753, 'Mcguire', 'Huangjing');
insert into aistore_address (customer_id, street, city) values (754, 'Gulseth', 'Bogojevo');
insert into aistore_address (customer_id, street, city) values (755, 'Emmet', 'Doropeti');
insert into aistore_address (customer_id, street, city) values (756, '1st', 'Yorii');
insert into aistore_address (customer_id, street, city) values (757, 'Buhler', 'Soledade');
insert into aistore_address (customer_id, street, city) values (758, 'Del Mar', 'Ghayl Bā Wazīr');
insert into aistore_address (customer_id, street, city) values (759, 'Hudson', 'Tanggung');
insert into aistore_address (customer_id, street, city) values (760, 'Birchwood', 'Tambov');
insert into aistore_address (customer_id, street, city) values (761, 'Starling', 'Eloy Alfaro');
insert into aistore_address (customer_id, street, city) values (762, 'Katie', 'Apartadó');
insert into aistore_address (customer_id, street, city) values (763, 'Meadow Valley', 'Detroit');
insert into aistore_address (customer_id, street, city) values (764, 'Milwaukee', 'Lévis');
insert into aistore_address (customer_id, street, city) values (765, 'Pepper Wood', 'Kout na Šumavě');
insert into aistore_address (customer_id, street, city) values (766, 'Carpenter', 'Kuanda');
insert into aistore_address (customer_id, street, city) values (767, 'Mendota', 'Oslo');
insert into aistore_address (customer_id, street, city) values (768, 'Haas', 'Bayt Liqyā');
insert into aistore_address (customer_id, street, city) values (769, 'Maple Wood', 'Mel’nikovo');
insert into aistore_address (customer_id, street, city) values (770, '7th', 'Jincheng');
insert into aistore_address (customer_id, street, city) values (771, 'Meadow Valley', 'Kaingiwa');
insert into aistore_address (customer_id, street, city) values (772, 'Gateway', 'Lianhe');
insert into aistore_address (customer_id, street, city) values (773, '6th', 'Tomsk');
insert into aistore_address (customer_id, street, city) values (774, 'Mcguire', 'Jönköping');
insert into aistore_address (customer_id, street, city) values (775, 'Summit', 'Nagaracinta');
insert into aistore_address (customer_id, street, city) values (776, 'Victoria', 'Kantemirovka');
insert into aistore_address (customer_id, street, city) values (777, 'Elgar', 'Qiawan');
insert into aistore_address (customer_id, street, city) values (778, 'Stephen', 'Dacun');
insert into aistore_address (customer_id, street, city) values (779, 'Russell', 'Santa Maria do Souto');
insert into aistore_address (customer_id, street, city) values (780, 'Clove', 'Budziszewice');
insert into aistore_address (customer_id, street, city) values (781, 'Sommers', 'Nova Olímpia');
insert into aistore_address (customer_id, street, city) values (782, 'Buhler', 'Lambangan Kulon');
insert into aistore_address (customer_id, street, city) values (783, 'Butterfield', 'Svalöv');
insert into aistore_address (customer_id, street, city) values (784, 'Badeau', 'Sakai');
insert into aistore_address (customer_id, street, city) values (785, '3rd', 'Sanquan');
insert into aistore_address (customer_id, street, city) values (786, 'Hintze', 'Jönköping');
insert into aistore_address (customer_id, street, city) values (787, 'Old Shore', 'Côte-Saint-Luc');
insert into aistore_address (customer_id, street, city) values (788, 'Almo', 'Nagasaki-shi');
insert into aistore_address (customer_id, street, city) values (789, 'Union', 'Jiangkou');
insert into aistore_address (customer_id, street, city) values (790, 'Heath', 'Independencia');
insert into aistore_address (customer_id, street, city) values (791, 'Golf View', 'Hejia');
insert into aistore_address (customer_id, street, city) values (792, 'Messerschmidt', 'Pira');
insert into aistore_address (customer_id, street, city) values (793, 'Red Cloud', 'Lukunor');
insert into aistore_address (customer_id, street, city) values (794, 'Waxwing', 'Huangrangping');
insert into aistore_address (customer_id, street, city) values (795, 'Banding', 'El Carril');
insert into aistore_address (customer_id, street, city) values (796, 'Arapahoe', 'Likwatang Timur');
insert into aistore_address (customer_id, street, city) values (797, 'Moulton', 'Oshawa');
insert into aistore_address (customer_id, street, city) values (798, 'Lerdahl', 'Loutráki');
insert into aistore_address (customer_id, street, city) values (799, 'Burrows', 'Dewetsdorp');
insert into aistore_address (customer_id, street, city) values (800, 'Northfield', 'Yangjia');
insert into aistore_address (customer_id, street, city) values (801, 'Morning', 'Själevad');
insert into aistore_address (customer_id, street, city) values (802, 'Prairieview', 'Vanadjou');
insert into aistore_address (customer_id, street, city) values (803, 'Hallows', 'Itajubá');
insert into aistore_address (customer_id, street, city) values (804, 'Village', 'Yujia’ao');
insert into aistore_address (customer_id, street, city) values (805, 'Pine View', 'Biting');
insert into aistore_address (customer_id, street, city) values (806, 'Elka', 'Bayanhoshuu');
insert into aistore_address (customer_id, street, city) values (807, 'Lakewood Gardens', 'Krajan Caluk');
insert into aistore_address (customer_id, street, city) values (808, 'Westend', 'San Juan');
insert into aistore_address (customer_id, street, city) values (809, 'Westridge', 'Bu‘eina');
insert into aistore_address (customer_id, street, city) values (810, 'Butterfield', 'Prince Albert');
insert into aistore_address (customer_id, street, city) values (811, 'Old Gate', 'Cuiabá');
insert into aistore_address (customer_id, street, city) values (812, 'Talmadge', 'Guan’e');
insert into aistore_address (customer_id, street, city) values (813, 'Mayer', 'Huntsville');
insert into aistore_address (customer_id, street, city) values (814, 'Bartillon', 'Gyangkar');
insert into aistore_address (customer_id, street, city) values (815, 'Roth', 'Nizhniy Bestyakh');
insert into aistore_address (customer_id, street, city) values (816, 'Memorial', 'Ibitinga');
insert into aistore_address (customer_id, street, city) values (817, 'Farmco', 'Otukpa');
insert into aistore_address (customer_id, street, city) values (818, 'Arapahoe', 'Wilga');
insert into aistore_address (customer_id, street, city) values (819, 'Almo', 'Acacías');
insert into aistore_address (customer_id, street, city) values (820, 'Nelson', 'Qionghai');
insert into aistore_address (customer_id, street, city) values (821, 'Fulton', 'Inowrocław');
insert into aistore_address (customer_id, street, city) values (822, 'Gina', 'Jiachuan');
insert into aistore_address (customer_id, street, city) values (823, 'Ridge Oak', 'Vlasenica');
insert into aistore_address (customer_id, street, city) values (824, 'Leroy', 'Vazhiny');
insert into aistore_address (customer_id, street, city) values (825, 'Ridgeview', 'La Esperanza');
insert into aistore_address (customer_id, street, city) values (826, 'Petterle', 'Zhoukou');
insert into aistore_address (customer_id, street, city) values (827, 'Armistice', 'Yelenendorf');
insert into aistore_address (customer_id, street, city) values (828, 'Dixon', 'Malishka');
insert into aistore_address (customer_id, street, city) values (829, 'Jana', 'Cochabamba');
insert into aistore_address (customer_id, street, city) values (830, 'Green', 'Pengchang');
insert into aistore_address (customer_id, street, city) values (831, 'Knutson', 'Tash-Kumyr');
insert into aistore_address (customer_id, street, city) values (832, 'Warner', 'Sanyantang');
insert into aistore_address (customer_id, street, city) values (833, 'Lien', 'Buang');
insert into aistore_address (customer_id, street, city) values (834, 'Heath', 'Sempol');
insert into aistore_address (customer_id, street, city) values (835, 'Graceland', 'Tange Zhen');
insert into aistore_address (customer_id, street, city) values (836, 'Bartillon', 'Takatsuki');
insert into aistore_address (customer_id, street, city) values (837, 'Clyde Gallagher', 'Ponikiew');
insert into aistore_address (customer_id, street, city) values (838, 'Sycamore', 'Kadupinang');
insert into aistore_address (customer_id, street, city) values (839, 'Kedzie', 'Kitob');
insert into aistore_address (customer_id, street, city) values (840, 'Riverside', 'Banjar Susut Kaja');
insert into aistore_address (customer_id, street, city) values (841, 'Bluejay', 'Zhanping');
insert into aistore_address (customer_id, street, city) values (842, 'Hagan', 'Solna');
insert into aistore_address (customer_id, street, city) values (843, 'Claremont', 'Milton');
insert into aistore_address (customer_id, street, city) values (844, 'Claremont', 'Loures');
insert into aistore_address (customer_id, street, city) values (845, 'Charing Cross', 'Boychinovtsi');
insert into aistore_address (customer_id, street, city) values (846, 'Lien', 'La Libertad');
insert into aistore_address (customer_id, street, city) values (847, 'Veith', 'Liucun');
insert into aistore_address (customer_id, street, city) values (848, 'Express', 'Kopychyntsi');
insert into aistore_address (customer_id, street, city) values (849, 'South', 'Pital');
insert into aistore_address (customer_id, street, city) values (850, 'Kim', 'Jinping');
insert into aistore_address (customer_id, street, city) values (851, 'Anzinger', 'Aduo');
insert into aistore_address (customer_id, street, city) values (852, 'Novick', 'San Juan');
insert into aistore_address (customer_id, street, city) values (853, 'Logan', 'Yaroslavskaya');
insert into aistore_address (customer_id, street, city) values (854, 'Del Sol', 'Xincun');
insert into aistore_address (customer_id, street, city) values (855, 'Gale', 'Insrom');
insert into aistore_address (customer_id, street, city) values (856, 'Canary', 'Suban Jeriji');
insert into aistore_address (customer_id, street, city) values (857, 'Lunder', 'Idhnā');
insert into aistore_address (customer_id, street, city) values (858, 'Pankratz', 'San José de Feliciano');
insert into aistore_address (customer_id, street, city) values (859, 'Colorado', 'Örnsköldsvik');
insert into aistore_address (customer_id, street, city) values (860, 'Toban', 'Mehar');
insert into aistore_address (customer_id, street, city) values (861, 'Wayridge', 'Ciudad Barrios');
insert into aistore_address (customer_id, street, city) values (862, 'Armistice', 'Dambulla');
insert into aistore_address (customer_id, street, city) values (863, 'Toban', 'Shuiyuesi');
insert into aistore_address (customer_id, street, city) values (864, 'Sutteridge', 'Kato Pyrgos');
insert into aistore_address (customer_id, street, city) values (865, 'Kim', 'Banjar Gunungpande');
insert into aistore_address (customer_id, street, city) values (866, 'Mccormick', 'Haugesund');
insert into aistore_address (customer_id, street, city) values (867, 'Linden', 'Palca');
insert into aistore_address (customer_id, street, city) values (868, 'Ludington', 'Blimbing');
insert into aistore_address (customer_id, street, city) values (869, 'High Crossing', 'Guarumal');
insert into aistore_address (customer_id, street, city) values (870, 'Declaration', 'La Virgen');
insert into aistore_address (customer_id, street, city) values (871, 'Heffernan', 'Gravatá');
insert into aistore_address (customer_id, street, city) values (872, 'Red Cloud', 'Cirompang');
insert into aistore_address (customer_id, street, city) values (873, 'Surrey', 'Odzi');
insert into aistore_address (customer_id, street, city) values (874, 'Warbler', 'Ocumare del Tuy');
insert into aistore_address (customer_id, street, city) values (875, 'Farwell', 'Meijiahe');
insert into aistore_address (customer_id, street, city) values (876, 'Mesta', 'Wuxi');
insert into aistore_address (customer_id, street, city) values (877, 'Fuller', 'Galatás');
insert into aistore_address (customer_id, street, city) values (878, 'Scott', 'Molchanovo');
insert into aistore_address (customer_id, street, city) values (879, 'Miller', 'Nagasaki-shi');
insert into aistore_address (customer_id, street, city) values (880, 'Dexter', 'Sampaloc');
insert into aistore_address (customer_id, street, city) values (881, 'Dixon', 'Newtown');
insert into aistore_address (customer_id, street, city) values (882, 'Melrose', 'Waepana');
insert into aistore_address (customer_id, street, city) values (883, 'Hagan', 'Szynwałd');
insert into aistore_address (customer_id, street, city) values (884, 'Blaine', 'Burirao');
insert into aistore_address (customer_id, street, city) values (885, 'Tony', 'Galis');
insert into aistore_address (customer_id, street, city) values (886, 'Village', 'Umeå');
insert into aistore_address (customer_id, street, city) values (887, 'Iowa', 'Xiatang');
insert into aistore_address (customer_id, street, city) values (888, 'Bultman', 'Barraute');
insert into aistore_address (customer_id, street, city) values (889, 'Oak Valley', 'Jampang Kulon');
insert into aistore_address (customer_id, street, city) values (890, 'Glacier Hill', 'Yuping');
insert into aistore_address (customer_id, street, city) values (891, 'Artisan', 'Hitachi-Naka');
insert into aistore_address (customer_id, street, city) values (892, 'Sycamore', 'Safi');
insert into aistore_address (customer_id, street, city) values (893, 'Arkansas', 'Barra do Corda');
insert into aistore_address (customer_id, street, city) values (894, 'Pearson', 'Francisco I Madero');
insert into aistore_address (customer_id, street, city) values (895, 'Fallview', 'Mulhouse');
insert into aistore_address (customer_id, street, city) values (896, 'Independence', 'Alibago');
insert into aistore_address (customer_id, street, city) values (897, 'Stone Corner', 'Puncaksari');
insert into aistore_address (customer_id, street, city) values (898, 'Mendota', 'Xiachu');
insert into aistore_address (customer_id, street, city) values (899, 'Parkside', 'Shenglilu');
insert into aistore_address (customer_id, street, city) values (900, 'Loeprich', 'Baní');
insert into aistore_address (customer_id, street, city) values (901, 'Meadow Ridge', 'Chicago');
insert into aistore_address (customer_id, street, city) values (902, 'Manitowish', 'Santo António da Charneca');
insert into aistore_address (customer_id, street, city) values (903, 'Mitchell', 'Montreuil');
insert into aistore_address (customer_id, street, city) values (904, 'Kenwood', 'Castainço');
insert into aistore_address (customer_id, street, city) values (905, 'Monica', 'Jianping');
insert into aistore_address (customer_id, street, city) values (906, 'Cody', 'La Cesira');
insert into aistore_address (customer_id, street, city) values (907, 'Mcbride', 'Huanan');
insert into aistore_address (customer_id, street, city) values (908, 'Del Mar', 'Sanzhang');
insert into aistore_address (customer_id, street, city) values (909, 'Jana', 'Baklashi');
insert into aistore_address (customer_id, street, city) values (910, 'Saint Paul', 'Blizne');
insert into aistore_address (customer_id, street, city) values (911, 'Ohio', 'Cisiec');
insert into aistore_address (customer_id, street, city) values (912, 'Warbler', 'Creil');
insert into aistore_address (customer_id, street, city) values (913, 'Waubesa', 'Camden');
insert into aistore_address (customer_id, street, city) values (914, 'Monterey', 'Colmar');
insert into aistore_address (customer_id, street, city) values (915, 'Stoughton', 'Bali');
insert into aistore_address (customer_id, street, city) values (916, 'American', 'Bålsta');
insert into aistore_address (customer_id, street, city) values (917, 'Florence', 'Pashiya');
insert into aistore_address (customer_id, street, city) values (918, 'Rigney', 'Santa Elena de Uairén');
insert into aistore_address (customer_id, street, city) values (919, 'Starling', 'Pengembur Dua');
insert into aistore_address (customer_id, street, city) values (920, 'Warrior', 'Gvozd');
insert into aistore_address (customer_id, street, city) values (921, 'Fairview', 'Yezhi');
insert into aistore_address (customer_id, street, city) values (922, 'Milwaukee', 'Chust Shahri');
insert into aistore_address (customer_id, street, city) values (923, 'Bonner', 'Mizque');
insert into aistore_address (customer_id, street, city) values (924, 'Blaine', 'Shāhpur');
insert into aistore_address (customer_id, street, city) values (925, 'Westport', 'Pueblo Nuevo');
insert into aistore_address (customer_id, street, city) values (926, 'Westport', 'Ciwaru');
insert into aistore_address (customer_id, street, city) values (927, 'School', 'Alta Gracia');
insert into aistore_address (customer_id, street, city) values (928, 'Center', 'Lizhuang');
insert into aistore_address (customer_id, street, city) values (929, 'Ramsey', 'Babakantugu');
insert into aistore_address (customer_id, street, city) values (930, 'Ohio', 'Bissau');
insert into aistore_address (customer_id, street, city) values (931, 'Dorton', 'Rasūlnagar');
insert into aistore_address (customer_id, street, city) values (932, 'Eastwood', 'Tabonoc');
insert into aistore_address (customer_id, street, city) values (933, 'Mesta', 'Fuenlabrada');
insert into aistore_address (customer_id, street, city) values (934, 'Barby', 'Marisol');
insert into aistore_address (customer_id, street, city) values (935, 'Northwestern', 'Sussex');
insert into aistore_address (customer_id, street, city) values (936, 'School', 'Ruse');
insert into aistore_address (customer_id, street, city) values (937, 'Holmberg', 'Nangang');
insert into aistore_address (customer_id, street, city) values (938, 'Emmet', 'Solţānābād');
insert into aistore_address (customer_id, street, city) values (939, 'Schurz', 'Mengla');
insert into aistore_address (customer_id, street, city) values (940, 'Steensland', 'Tembladera');
insert into aistore_address (customer_id, street, city) values (941, 'Moland', 'Umeå');
insert into aistore_address (customer_id, street, city) values (942, 'Lunder', 'Jaša Tomić');
insert into aistore_address (customer_id, street, city) values (943, 'Atwood', 'Jianli');
insert into aistore_address (customer_id, street, city) values (944, 'Knutson', 'Yelenendorf');
insert into aistore_address (customer_id, street, city) values (945, 'Nova', 'Kazanskoye');
insert into aistore_address (customer_id, street, city) values (946, 'Harbort', 'Gaobeijie');
insert into aistore_address (customer_id, street, city) values (947, 'Reindahl', 'Saint-Rémi');
insert into aistore_address (customer_id, street, city) values (948, 'Morningstar', 'Krzeszów');
insert into aistore_address (customer_id, street, city) values (949, 'Dennis', 'Sakado');
insert into aistore_address (customer_id, street, city) values (950, 'Melvin', 'Mekarjaya');
insert into aistore_address (customer_id, street, city) values (951, 'Hooker', 'Batarasa');
insert into aistore_address (customer_id, street, city) values (952, 'Brown', 'Aygeshat');
insert into aistore_address (customer_id, street, city) values (953, 'Grim', 'Dandu');
insert into aistore_address (customer_id, street, city) values (954, 'Packers', '‘Ābūd');
insert into aistore_address (customer_id, street, city) values (955, 'Bobwhite', 'Gao');
insert into aistore_address (customer_id, street, city) values (956, 'Morrow', 'Gogaran');
insert into aistore_address (customer_id, street, city) values (957, 'La Follette', 'Ruyigi');
insert into aistore_address (customer_id, street, city) values (958, 'Lake View', 'Manicaragua');
insert into aistore_address (customer_id, street, city) values (959, 'Namekagon', 'Juiz de Fora');
insert into aistore_address (customer_id, street, city) values (960, 'Grasskamp', 'Lingquan');
insert into aistore_address (customer_id, street, city) values (961, 'Butterfield', 'Yuntan');
insert into aistore_address (customer_id, street, city) values (962, 'Rieder', 'Kabacan');
insert into aistore_address (customer_id, street, city) values (963, 'Russell', 'Dembeni');
insert into aistore_address (customer_id, street, city) values (964, 'Eagle Crest', 'Bassano');
insert into aistore_address (customer_id, street, city) values (965, 'Eastwood', 'Shangqing');
insert into aistore_address (customer_id, street, city) values (966, 'Morning', 'Jakhaly');
insert into aistore_address (customer_id, street, city) values (967, 'Loomis', 'San Antonio');
insert into aistore_address (customer_id, street, city) values (968, 'Thompson', 'Nikolayevka');
insert into aistore_address (customer_id, street, city) values (969, 'Namekagon', 'Paris La Défense');
insert into aistore_address (customer_id, street, city) values (970, 'Carey', 'Vilhelmina');
insert into aistore_address (customer_id, street, city) values (971, 'Hanson', 'Gumi');
insert into aistore_address (customer_id, street, city) values (972, 'Corben', 'Lille');
insert into aistore_address (customer_id, street, city) values (973, 'Katie', 'Az̧ Z̧alī‘ah');
insert into aistore_address (customer_id, street, city) values (974, 'Harbort', 'Bajiao');
insert into aistore_address (customer_id, street, city) values (975, 'Victoria', 'Beloyarskiy');
insert into aistore_address (customer_id, street, city) values (976, 'Maryland', 'Tiblawan');
insert into aistore_address (customer_id, street, city) values (977, 'Walton', 'Asahi');
insert into aistore_address (customer_id, street, city) values (978, 'Stone Corner', 'Lamovita');
insert into aistore_address (customer_id, street, city) values (979, 'Graceland', 'Tongyu');
insert into aistore_address (customer_id, street, city) values (980, 'Service', 'Haoyi');
insert into aistore_address (customer_id, street, city) values (981, 'Ridge Oak', 'Huadian');
insert into aistore_address (customer_id, street, city) values (982, 'Troy', 'Independencia');
insert into aistore_address (customer_id, street, city) values (983, 'Hoepker', 'Chamlykskaya');
insert into aistore_address (customer_id, street, city) values (984, 'Warbler', 'Bosaso');
insert into aistore_address (customer_id, street, city) values (985, '3rd', 'Dalar');
insert into aistore_address (customer_id, street, city) values (986, 'Talmadge', 'Ḩājjīābād');
insert into aistore_address (customer_id, street, city) values (987, 'Gale', 'La Unión');
insert into aistore_address (customer_id, street, city) values (988, 'Burrows', 'Mungwi');
insert into aistore_address (customer_id, street, city) values (989, 'Coolidge', 'Sebina');
insert into aistore_address (customer_id, street, city) values (990, 'Caliangt', 'Dębno');
insert into aistore_address (customer_id, street, city) values (991, 'Fairfield', 'Xinglong');
insert into aistore_address (customer_id, street, city) values (992, 'American', 'Zomba');
insert into aistore_address (customer_id, street, city) values (993, 'Granby', 'Barra do Corda');
insert into aistore_address (customer_id, street, city) values (994, 'Brickson Park', 'Náousa');
insert into aistore_address (customer_id, street, city) values (995, 'Annamark', 'Falāvarjān');
insert into aistore_address (customer_id, street, city) values (996, 'Merry', 'Ülken');
insert into aistore_address (customer_id, street, city) values (997, 'Reindahl', 'Mingelchaur');
insert into aistore_address (customer_id, street, city) values (998, 'Colorado', 'Ziyuan');
insert into aistore_address (customer_id, street, city) values (999, 'Monica', 'Zgłobień');
insert into aistore_address (customer_id, street, city) values (1000, 'Fair Oaks', 'Wissembourg');
