# Generated by Django 5.2.8 on 2025-11-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='slug',
        ),
    ]
