# Generated by Django 5.2.8 on 2025-11-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sshinfo',
            old_name='loginId',
            new_name='login_id',
        ),
    ]
